version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/test/columns"
      - "/test/e2e/truncation"
      - "/test/document_storage_tests/documents_tests"
      - "/test/document_storage_tests/documents_tests_deprecated"
      - "/tools/mkdb"
      - "/docs/security/vulnerabilities/linear-fake/go"
      - "/docs/security/vulnerabilities/linear-fake/server"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"