version = 1

test_patterns = [
    "test/**",
    "**_test.go"
]

exclude_patterns = [
    "build/**",
    "tools/**",
    "configs/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/codenotary/immudb"]