ignore:
  - "*windows.go"
  - "*freebsd.go"
  - "*windows.dist.go"
  - "*freebsd.dist.go"
  - "*windows*"
  - "*freebsd*"
  - "cmd/immuadmin/command/service/servicetest"
  - "pkg/client/clienttest"
  - "cmd/immuadmin/command/service/oss_unix.go"
  - "cmd/immuclient/immuctest"
