{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "immudb.fullname" . }}-config
  labels:
    {{- include "immudb.labels" . | nindent 4 }}
data:
  immudb.toml: |
{{ .Values.config.data | indent 4 }}
{{- end }}