{{ if $.Values.adminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "immudb.fullname" . }}-credentials
  labels:
    {{- include "immudb.labels" . | nindent 4 }}
type: Opaque 
data: 
  immudb-admin-password: "{{$.Values.adminPassword|b64enc}}"
{{ end }}
