apiVersion: v1
kind: Service
metadata:
  name: {{ include "immudb.fullname" . }}-http
  labels:
    {{- include "immudb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "immudb.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "immudb.fullname" . }}-grpc
  labels:
    {{- include "immudb.labels" . | nindent 4 }}
  annotations:  
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "immudb.selectorLabels" . | nindent 4 }}
