/*
 * immudb REST API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SchemaSignature struct {
	PublicKey string `json:"publicKey,omitempty"`
	Signature string `json:"signature,omitempty"`
}
