/*
 * immudb REST API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Schemav2DocumentQuery struct {
	Field string `json:"field,omitempty"`
	Operator *Schemav2QueryOperator `json:"operator,omitempty"`
	Value interface{} `json:"value,omitempty"`
}
