/*
 * immudb REST API v2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Schemav2QueryOperator string

// List of schemav2QueryOperator
const (
	EQ Schemav2QueryOperator = "EQ"
	GT Schemav2QueryOperator = "GT"
	GTE Schemav2QueryOperator = "GTE"
	LT Schemav2QueryOperator = "LT"
	LTE Schemav2QueryOperator = "LTE"
	LIKE Schemav2QueryOperator = "LIKE"
)
