/*
Copyright 2026 Codenotary Inc. All rights reserved.

SPDX-License-Identifier: BUSL-1.1
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://mariadb.com/bsl11/

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package sys

import (
	"context"

	"github.com/codenotary/immudb/embedded/sql"
)

// pg_attribute: one row per column per user table. attrelid links back
// to pg_class via relOID("public", table.Name()) — the same scheme
// used on the pg_class side, so JOINs between them work.
//
// attnum is 1-based (matching PG). immudb's Column.ID() happens to be
// 1-based too; we use it directly so attnum order matches column-
// declaration order, which is what psql's \d expects.
func init() {
	sql.RegisterSystemTable(&sql.SystemTableDef{
		Name: "pg_attribute",
		Columns: []sql.SystemTableColumn{
			{Name: "attrelid", Type: sql.IntegerType},
			{Name: "attname", Type: sql.VarcharType, MaxLen: 128},
			{Name: "atttypid", Type: sql.IntegerType},
			{Name: "attstattarget", Type: sql.IntegerType},
			{Name: "attlen", Type: sql.IntegerType},
			{Name: "attnum", Type: sql.IntegerType},
			{Name: "attndims", Type: sql.IntegerType},
			{Name: "attcacheoff", Type: sql.IntegerType},
			{Name: "atttypmod", Type: sql.IntegerType},
			{Name: "attbyval", Type: sql.BooleanType},
			{Name: "attstorage", Type: sql.VarcharType, MaxLen: 1},
			{Name: "attalign", Type: sql.VarcharType, MaxLen: 1},
			{Name: "attnotnull", Type: sql.BooleanType},
			{Name: "atthasdef", Type: sql.BooleanType},
			{Name: "atthasmissing", Type: sql.BooleanType},
			{Name: "attidentity", Type: sql.VarcharType, MaxLen: 1},
			{Name: "attgenerated", Type: sql.VarcharType, MaxLen: 1},
			{Name: "attisdropped", Type: sql.BooleanType},
			{Name: "attislocal", Type: sql.BooleanType},
			{Name: "attinhcount", Type: sql.IntegerType},
			{Name: "attcollation", Type: sql.IntegerType},
			{Name: "attoid", Type: sql.IntegerType}, // non-standard but pgAdmin reads it
		},
		// attrelid alone isn't unique (each table has many rows) but
		// the registry needs a PK column — use attoid which we
		// synthesize per (table, column).
		PKColumn: "attoid",
		Scan: func(ctx context.Context, tx *sql.SQLTx) ([]*sql.Row, error) {
			cat := tx.Catalog()
			if cat == nil {
				return nil, nil
			}

			tables := cat.GetTables()
			// Rough pre-size: average 8 cols per table.
			rows := make([]*sql.Row, 0, len(tables)*8)

			for _, t := range tables {
				relid := relOID("public", t.Name())

				// immudb's Column.IsNullable() reports the literal
				// NOT NULL flag; PostgreSQL additionally treats every
				// PK member as implicitly NOT NULL. Mirror PG so psql
				// \d shows the right "not null" marker.
				pkCols := map[string]struct{}{}
				if pk := t.PrimaryIndex(); pk != nil {
					for _, c := range pk.Cols() {
						pkCols[c.Name()] = struct{}{}
					}
				}

				for _, col := range t.Cols() {
					_, isPK := pkCols[col.Name()]
					rows = append(rows, rowPgAttribute(relid, t.Name(), col, isPK))
				}
			}
			return rows, nil
		},
	})
}

func rowPgAttribute(relid int64, tableName string, col *sql.Column, isPK bool) *sql.Row {
	identity := ""
	if col.IsAutoIncremental() {
		identity = "d" // generated by default as identity
	}

	attbyval := false
	switch col.Type() {
	case sql.IntegerType, sql.BooleanType, sql.Float64Type:
		attbyval = true
	}

	// PG semantics: any PK column is NOT NULL, regardless of whether
	// the user wrote NOT NULL explicitly.
	notNull := !col.IsNullable() || isPK

	return &sql.Row{ValuesByPosition: []sql.TypedValue{
		sql.NewInteger(relid),
		sql.NewVarchar(col.Name()),
		sql.NewInteger(pgTypeOIDForSQLType(col.Type())),
		sql.NewInteger(-1), // attstattarget
		sql.NewInteger(pgTypeLenForSQLType(col.Type())),
		sql.NewInteger(int64(col.ID())),
		sql.NewInteger(0),  // attndims — we don't expose array types
		sql.NewInteger(-1), // attcacheoff
		sql.NewInteger(attTypmodFor(col)),
		sql.NewBool(attbyval),
		sql.NewVarchar(attStorageFor(col.Type())),
		sql.NewVarchar(attAlignFor(col.Type())),
		sql.NewBool(notNull),
		sql.NewBool(col.HasDefault()),
		sql.NewBool(false), // atthasmissing
		varcharOrNullIfEmpty(identity),
		sql.NewVarchar(""), // attgenerated — empty string = not generated
		sql.NewBool(false),
		sql.NewBool(true), // attislocal
		sql.NewInteger(0), // attinhcount
		sql.NewInteger(0), // attcollation
		sql.NewInteger(colOID("public", tableName, col.Name())),
	}}
}

// attTypmodFor encodes VARCHAR(N)'s N for psql's format_type(). PG's
// typmod encoding for varchar is `maxlen + 4`; we mirror it so
// format_type (once wired up) can decode cleanly.
func attTypmodFor(col *sql.Column) int64 {
	if col.Type() == sql.VarcharType && col.MaxLen() > 0 {
		return int64(col.MaxLen()) + 4
	}
	return -1
}

// attStorageFor returns the PG TOAST storage code. Fixed-width types
// are 'p' (plain); variable-width get 'x' (extended / compressible).
// Clients that don't care about TOAST ignore the column, but pgAdmin
// filters on it.
func attStorageFor(t sql.SQLValueType) string {
	switch t {
	case sql.BooleanType, sql.IntegerType, sql.Float64Type,
		sql.UUIDType, sql.TimestampType:
		return "p"
	default:
		return "x"
	}
}

// attAlignFor returns the alignment code PG stores. 'c' = char, 'i' =
// int (4-byte), 'd' = double (8-byte). Reasonable defaults by type.
func attAlignFor(t sql.SQLValueType) string {
	switch t {
	case sql.BooleanType:
		return "c"
	case sql.IntegerType, sql.Float64Type, sql.TimestampType, sql.UUIDType:
		return "d"
	default:
		return "i"
	}
}

func varcharOrNullIfEmpty(s string) sql.TypedValue {
	if s == "" {
		return sql.NewNull(sql.VarcharType)
	}
	return sql.NewVarchar(s)
}
