#! /usr/bin/env bash

# chkconfig: 2345 80 05
# description: immudb database
# processname: immudb
# config: /etc/immudb/immudb.toml
# pidfile: /var/run/immudb.pid

### BEGIN INIT INFO
# Provides:          immudb
# Required-Start:    $all
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start immudb at boot time
### END INIT INFO

#  tested on
#  1. New lsb that define start-stop-daemon
#  3. Centos with initscripts package installed

PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=immudb
DESC="immud - the tamperproof database"
DEFAULT=/etc/default/$NAME

IMMU_USER=immu
IMMU_GROUP=immu
IMMU_HOME=/usr/share/immudb
CONF_DIR=/etc/immudb
WORK_DIR=$IMMU_HOME
DATA_DIR=/var/lib/immudb
LOG_DIR=/var/log/immudb
CONF_FILE=$CONF_DIR/immudb.toml
MAX_OPEN_FILES=10000
PID_FILE=/var/run/$NAME.pid
DAEMON=/usr/sbin/$NAME

umask 0027

if [ ! -x $DAEMON ]; then
  echo "Program not installed or not executable"
  exit 5
fi

. /lib/lsb/init-functions

if [ -r /etc/default/rcS ]; then
	. /etc/default/rcS
fi

# overwrite settings from default file
if [ -f "$DEFAULT" ]; then
	. "$DEFAULT"
fi

DAEMON_OPTS="--config ${CONF_FILE}"

function checkUser() {
  if [ `id -u` -ne 0 ]; then
  	echo "You need root privileges to run this script"
  	exit 4
  fi
}

case "$1" in
  start)
  checkUser
	log_daemon_msg "Starting $DESC"

	pid=`pidofproc -p $PID_FILE immud`
	if [ -n "$pid" ] ; then
		log_begin_msg "Already running."
		log_end_msg 0
		exit 0
	fi

	# Prepare environment
	mkdir -p "$LOG_DIR" "$DATA_DIR" && chown "$IMMU_USER":"$IMMU_GROUP" "$LOG_DIR" "$DATA_DIR"
	touch "$PID_FILE" && chown "$IMMU_USER":"$IMMU_GROUP" "$PID_FILE"

  if [ -n "$MAX_OPEN_FILES" ]; then
		ulimit -n $MAX_OPEN_FILES
	fi

	# Start Daemon
	start-stop-daemon --start -b --chdir "$WORK_DIR" --user "$IMMU_USER" -c "$IMMU_USER" --pidfile "$PID_FILE" --exec $DAEMON -- $DAEMON_OPTS
	return=$?
	if [ $return -eq 0 ]
	then
	  sleep 1

    # check if pid file has been written to
	  if ! [[ -s $PID_FILE ]]; then
	    log_end_msg 1
	    exit 1
	  fi

		i=0
		timeout=10
		# Wait for the process to be properly started before exiting
		until { cat "$PID_FILE" | xargs kill -0; } >/dev/null 2>&1
		do
			sleep 1
			i=$(($i + 1))
      if [ $i -gt $timeout ]; then
			  log_end_msg 1
			  exit 1
			fi
		done
  fi
  log_end_msg $return
	;;
  stop)
  checkUser
	log_daemon_msg "Stopping $DESC"

	if [ -f "$PID_FILE" ]; then
		start-stop-daemon --stop --pidfile "$PID_FILE" \
			--user "$IMMU_USER" \
			--retry=TERM/20/KILL/5 >/dev/null
		if [ $? -eq 1 ]; then
			log_progress_msg "$DESC is not running but pid file exists, cleaning up"
		elif [ $? -eq 3 ]; then
			PID="`cat $PID_FILE`"
			log_failure_msg "Failed to stop $DESC (pid $PID)"
			exit 1
		fi
		rm -f "$PID_FILE"
	else
		log_progress_msg "(not running)"
	fi
	log_end_msg 0
	;;
  status)
	status_of_proc -p $PID_FILE immudb immudb && exit 0 || exit $?
    ;;
  restart|force-reload)
	if [ -f "$PID_FILE" ]; then
		$0 stop
		sleep 1
	fi
	$0 start
	;;
  *)
	log_success_msg "Usage: $0 {start|stop|restart|force-reload|status}"
	exit 3
	;;
esac
