/*
Copyright 2026 Codenotary Inc. All rights reserved.

SPDX-License-Identifier: BUSL-1.1
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://mariadb.com/bsl11/

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package sql

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
)

// Reproducer for the two Gitea/XORM repoStatsCheck boot errors observed
// against a build of feat/auditlog:
//
//	models/repo.go:37 Select label count 'num_closed_issues':
//	  pq: syntax error: unexpected IDENTIFIER, expecting LATERAL at position 97
//	models/repo.go:37 Select issue count 'num_comments':
//	  pq: got 2 parameters but the statement requires 0
//
// Both involve the same shape: a scalar subquery in WHERE that references
// two `$N` bind parameters in its own nested WHERE.

// giteaStatsCheckSQL is the exact query captured from the immudb db log
// during Gitea boot. It must parse cleanly and inferParameters must
// report exactly two AnyType/Boolean parameters.
const giteaStatsCheckSQL = `SELECT repo.id FROM repository repo WHERE repo.num_closed_issues != (SELECT COUNT(*) FROM issue WHERE repo_id = repo.id AND is_closed = $1 AND is_pull = $2)`

// giteaLabelStatSQL is the REAL query that produced Error 1. It uses a
// comma-join `FROM issue_label, issue` in the scalar subquery — classic
// SQL-89 implicit cross-join — and immudb's grammar currently requires
// a LATERAL keyword after the comma. Position 97 in this query lands
// on the `issue` table name after the comma, matching the reported
// "unexpected IDENTIFIER, expecting LATERAL at position 97".
const giteaLabelStatSQL = `SELECT label.id FROM label WHERE label.num_closed_issues != (SELECT COUNT(*) FROM issue_label, issue WHERE issue_label.label_id = label.id AND issue_label.issue_id = issue.id AND issue.is_closed = $1)`

// TestScalarSubQueryInWhere_ParseSucceeds decides between the two live
// hypotheses for Error 1:
//   - If ParseSQLString accepts giteaStatsCheckSQL, the engine grammar is
//     fine and the pgsql wire-layer rewrite pipeline is the corruptor.
//   - If ParseSQLString rejects it with the same "expecting LATERAL"
//     error, the fix belongs in embedded/sql/sql_grammar.y.
//
// The test asserts the grammar accepts the shape; on regression it fails
// loud and tells the reader which hypothesis applies.
func TestScalarSubQueryInWhere_ParseSucceeds(t *testing.T) {
	_, err := ParseSQLString(giteaStatsCheckSQL)
	require.NoErrorf(t, err,
		"engine grammar must accept the Gitea repoStatsCheck shape (scalar subquery in WHERE with $N bind markers); "+
			"if this fails, Error 1 is a grammar bug (sql_grammar.y), not a pgsql wire-layer rewrite bug")
}

// TestCommaJoinInScalarSubquery_ParseSucceeds is the actual Error 1 guard.
// Gitea's labelStatsQueryNumIssues uses `FROM issue_label, issue` — a
// SQL-89 implicit cross-join — inside the scalar subquery. PG accepts
// this form (equivalent to `FROM issue_label CROSS JOIN issue`), but
// immudb's grammar only accepts `, LATERAL ds` after the comma, so the
// parser errors at the bare table name with "unexpected IDENTIFIER,
// expecting LATERAL at position N".
func TestCommaJoinInScalarSubquery_ParseSucceeds(t *testing.T) {
	_, err := ParseSQLString(giteaLabelStatSQL)
	require.NoErrorf(t, err,
		"engine grammar must accept implicit comma-joins in FROM (SQL-89 cross-join syntax); "+
			"Gitea's labelStatsQueryNumIssues is the canonical repro")
}

// giteaIssueNumCommentsSQL is the real Error 2 repro. Generated by
// XORM's builder from Gitea's "issue count 'num_comments'" stat
// checker. `type IN ($1, $2)` expands ConversationCountedCommentType
// (= [CommentTypeComment, CommentTypeReview]) into two bind markers.
const giteaIssueNumCommentsSQL = `SELECT issue.id FROM issue WHERE issue.num_comments != (SELECT COUNT(*) FROM comment WHERE issue_id = issue.id AND type IN ($1, $2))`

// TestInListInScalarSubquery_InferParameters is the Error 2 guard.
// The outer SelectStmt's inferParameters must recurse into the scalar
// subquery's WHERE — otherwise the IN-list's two markers stay
// unregistered and the pgsql ParameterDescription sends 0 to the
// client, which then fails at Bind with
// "got 2 parameters but statement requires 0".
func TestInListInScalarSubquery_InferParameters(t *testing.T) {
	engine := setupCommonTest(t)
	ctx := context.Background()

	mustExec := func(stmt string) {
		t.Helper()
		_, _, err := engine.Exec(ctx, nil, stmt, nil)
		require.NoError(t, err, stmt)
	}
	mustExec(`CREATE TABLE issue (id INTEGER NOT NULL, num_comments INTEGER, PRIMARY KEY(id));`)
	mustExec(`CREATE TABLE comment (id INTEGER NOT NULL, issue_id INTEGER, type INTEGER, PRIMARY KEY(id));`)

	params, err := engine.InferParameters(ctx, nil, giteaIssueNumCommentsSQL)
	require.NoError(t, err)
	require.Lenf(t, params, 2,
		"inferParameters must find both IN-list markers inside the scalar subquery; got %v", params)
	require.Contains(t, params, "param1")
	require.Contains(t, params, "param2")
}

// TestScalarSubQueryInWhere_InferParameters pins Error 2: the outer
// SelectStmt's inferParameters must recurse into the scalar subquery's
// WHERE so $1 and $2 surface in the ParameterDescription the pgsql wire
// sends back to the client. Without the walk, lib/pq sees a 0-param
// description and fails at Bind with "got 2 parameters but statement
// requires 0".
func TestScalarSubQueryInWhere_InferParameters(t *testing.T) {
	engine := setupCommonTest(t)
	ctx := context.Background()

	// Schema mirrors Gitea's repository + issue tables to the extent the
	// stats-check query touches them. Types are intentionally minimal.
	mustExec := func(stmt string) {
		t.Helper()
		_, _, err := engine.Exec(ctx, nil, stmt, nil)
		require.NoError(t, err, stmt)
	}
	mustExec(`CREATE TABLE repository (
		id INTEGER NOT NULL,
		num_closed_issues INTEGER,
		PRIMARY KEY(id)
	);`)
	mustExec(`CREATE TABLE issue (
		id INTEGER NOT NULL,
		repo_id INTEGER,
		is_closed BOOLEAN,
		is_pull BOOLEAN,
		PRIMARY KEY(id)
	);`)

	params, err := engine.InferParameters(ctx, nil, giteaStatsCheckSQL)
	require.NoError(t, err)
	require.Lenf(t, params, 2,
		"inferParameters must recurse into the scalar subquery's WHERE to find $1 and $2; got %v", params)
	require.Containsf(t, params, "param1",
		"param1 must be registered by inferParameters; got %v", params)
	require.Containsf(t, params, "param2",
		"param2 must be registered by inferParameters; got %v", params)
}

// TestInSubQueryInWhere_InferParameters is the Gitea GetUserOrgsList
// repro. XORM's builder lowers `builder.In(col, subquery)` to the
// `col IN (SELECT …)` shape, which the grammar parses to
// *InSubQueryExp. The subquery's WHERE carries the $N marker; the
// outer SelectStmt.inferParameters must descend into it. Without the
// fix, the pgsql ParameterDescription reports 0 params and lib/pq
// rejects the client's 1-value Bind with "got 1 parameters but the
// statement requires 0".
func TestInSubQueryInWhere_InferParameters(t *testing.T) {
	engine := setupCommonTest(t)
	ctx := context.Background()

	mustExec := func(stmt string) {
		t.Helper()
		_, _, err := engine.Exec(ctx, nil, stmt, nil)
		require.NoError(t, err, stmt)
	}
	mustExec(`CREATE TABLE u (id INTEGER NOT NULL, name VARCHAR, PRIMARY KEY(id));`)
	mustExec(`CREATE TABLE ou (id INTEGER NOT NULL, uid INTEGER, org_id INTEGER, PRIMARY KEY(id));`)

	params, err := engine.InferParameters(ctx, nil,
		`SELECT id FROM u WHERE id IN (SELECT org_id FROM ou WHERE uid = $1)`)
	require.NoError(t, err)
	require.Lenf(t, params, 1,
		"inferParameters must descend into the IN-subquery's WHERE; got %v", params)
	require.Contains(t, params, "param1")
}

// TestExistsSubQueryInWhere_InferParameters — `WHERE EXISTS (SELECT …
// WHERE x = $1)` is the other correlated-subquery shape ORMs emit for
// nullable-reference checks. *ExistsBoolExp holds a DataSource `q`;
// the walker must type-assert to *SelectStmt and recurse.
func TestExistsSubQueryInWhere_InferParameters(t *testing.T) {
	engine := setupCommonTest(t)
	ctx := context.Background()

	mustExec := func(stmt string) {
		t.Helper()
		_, _, err := engine.Exec(ctx, nil, stmt, nil)
		require.NoError(t, err, stmt)
	}
	mustExec(`CREATE TABLE t (id INTEGER NOT NULL, PRIMARY KEY(id));`)
	mustExec(`CREATE TABLE q (id INTEGER NOT NULL, x INTEGER, PRIMARY KEY(id));`)

	params, err := engine.InferParameters(ctx, nil,
		`SELECT id FROM t WHERE EXISTS (SELECT 1 FROM q WHERE x = $1)`)
	require.NoError(t, err)
	require.Lenf(t, params, 1,
		"inferParameters must descend into the EXISTS subquery's WHERE; got %v", params)
	require.Contains(t, params, "param1")
}

// TestGroupByAlias_OrderByAlias_InferParameters — Gitea's heatmap
// query uses `SELECT expr AS timestamp … GROUP BY timestamp ORDER BY
// timestamp`. The GROUP BY references the SELECT alias, not the raw
// expression; the aggregation check must treat that as valid.
func TestGroupByAlias_OrderByAlias_InferParameters(t *testing.T) {
	engine := setupCommonTest(t)
	ctx := context.Background()

	_, _, err := engine.Exec(ctx, nil,
		`CREATE TABLE action (id INTEGER NOT NULL, user_id INTEGER, act_user_id INTEGER, created_unix INTEGER, PRIMARY KEY(id));`, nil)
	require.NoError(t, err)

	_, err = engine.InferParameters(ctx, nil,
		`SELECT created_unix / 900 * 900 AS timestamp, count(user_id) AS contributions `+
			`FROM action WHERE (user_id = $1 AND act_user_id = $2) AND created_unix > $3 `+
			`GROUP BY timestamp ORDER BY timestamp`)
	require.NoError(t, err,
		"aggregation check must accept GROUP BY / ORDER BY of a SELECT alias when the target carries AS <alias>")

	// Also the no-AS-on-COUNT variant, matching the literal SQL Gitea's
	// heatmap generates.
	_, err = engine.InferParameters(ctx, nil,
		`SELECT created_unix / 900 * 900 AS timestamp, count(user_id) `+
			`FROM action WHERE (user_id = $1 AND act_user_id = $2) AND created_unix > $3 `+
			`GROUP BY timestamp ORDER BY timestamp`)
	require.NoError(t, err, "same shape without AS on the aggregate target must also be accepted")

	// Also attempt to Exec it — the aggregation check runs on both paths.
	_, _, err = engine.Exec(ctx, nil,
		`SELECT created_unix / 900 * 900 AS timestamp, count(user_id) `+
			`FROM action WHERE (user_id = 1 AND act_user_id = 1) AND created_unix > 0 `+
			`GROUP BY timestamp ORDER BY timestamp;`, nil)
	require.NoError(t, err, "Exec path must accept the same query")
}

// TestTypeNameAsAlias_Parses — Gitea's heatmap SELECT uses
// `AS timestamp` as an alias; Postgres accepts reserved type names
// as identifiers in alias position, immudb now does too.
func TestTypeNameAsAlias_Parses(t *testing.T) {
	_, err := ParseSQLString(
		`SELECT created_unix / 900 * 900 AS timestamp, count(user_id) AS contributions FROM action GROUP BY timestamp`)
	require.NoError(t, err,
		"grammar must accept reserved type names (TIMESTAMP, INTEGER, VARCHAR, …) as column aliases")
}

// TestCountDistinctWithParens_Parses pins `COUNT(DISTINCT(col))` — the
// extra-paren form XORM's builder emits for Gitea GetUserOrgsList's
// per-org repo count. Grammar accepts it as equivalent to
// COUNT(DISTINCT col).
func TestCountDistinctWithParens_Parses(t *testing.T) {
	_, err := ParseSQLString(
		`SELECT owner_id AS org_id, COUNT(DISTINCT(repository.id)) AS repo_count FROM repository GROUP BY owner_id`)
	require.NoError(t, err,
		"grammar must accept COUNT(DISTINCT(col)) — the parenthesized XORM variant")
}

// TestCaseWhenWithBindParam_InferParameters — $N can hide inside the
// WHEN/THEN arms of a CASE expression in the SELECT list. ORMs emit
// conditional aggregations in this shape. *CaseWhenExp has exp,
// whenThen[], elseExp, all of which the walker must descend into.
func TestCaseWhenWithBindParam_InferParameters(t *testing.T) {
	engine := setupCommonTest(t)
	ctx := context.Background()

	_, _, err := engine.Exec(ctx, nil,
		`CREATE TABLE t (id INTEGER NOT NULL, x INTEGER, PRIMARY KEY(id));`, nil)
	require.NoError(t, err)

	params, err := engine.InferParameters(ctx, nil,
		`SELECT CASE WHEN x = $1 THEN 'y' ELSE 'n' END AS label FROM t`)
	require.NoError(t, err)
	require.Lenf(t, params, 1,
		"inferParameters must descend into CASE/WHEN arms; got %v", params)
	require.Contains(t, params, "param1")
}
