// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package schema

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Key struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type KeyValue struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Index struct {
	Index                uint64   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{2}
}

func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type Item struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Index                uint64   `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{3}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Item) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Item) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type KVList struct {
	KVs                  []*KeyValue `protobuf:"bytes,1,rep,name=KVs,proto3" json:"KVs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *KVList) Reset()         { *m = KVList{} }
func (m *KVList) String() string { return proto.CompactTextString(m) }
func (*KVList) ProtoMessage()    {}
func (*KVList) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{4}
}

func (m *KVList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVList.Unmarshal(m, b)
}
func (m *KVList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVList.Marshal(b, m, deterministic)
}
func (m *KVList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVList.Merge(m, src)
}
func (m *KVList) XXX_Size() int {
	return xxx_messageInfo_KVList.Size(m)
}
func (m *KVList) XXX_DiscardUnknown() {
	xxx_messageInfo_KVList.DiscardUnknown(m)
}

var xxx_messageInfo_KVList proto.InternalMessageInfo

func (m *KVList) GetKVs() []*KeyValue {
	if m != nil {
		return m.KVs
	}
	return nil
}

type KeyList struct {
	Keys                 []*Key   `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyList) Reset()         { *m = KeyList{} }
func (m *KeyList) String() string { return proto.CompactTextString(m) }
func (*KeyList) ProtoMessage()    {}
func (*KeyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{5}
}

func (m *KeyList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyList.Unmarshal(m, b)
}
func (m *KeyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyList.Marshal(b, m, deterministic)
}
func (m *KeyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyList.Merge(m, src)
}
func (m *KeyList) XXX_Size() int {
	return xxx_messageInfo_KeyList.Size(m)
}
func (m *KeyList) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyList.DiscardUnknown(m)
}

var xxx_messageInfo_KeyList proto.InternalMessageInfo

func (m *KeyList) GetKeys() []*Key {
	if m != nil {
		return m.Keys
	}
	return nil
}

type ItemList struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemList) Reset()         { *m = ItemList{} }
func (m *ItemList) String() string { return proto.CompactTextString(m) }
func (*ItemList) ProtoMessage()    {}
func (*ItemList) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{6}
}

func (m *ItemList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemList.Unmarshal(m, b)
}
func (m *ItemList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemList.Marshal(b, m, deterministic)
}
func (m *ItemList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemList.Merge(m, src)
}
func (m *ItemList) XXX_Size() int {
	return xxx_messageInfo_ItemList.Size(m)
}
func (m *ItemList) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemList.DiscardUnknown(m)
}

var xxx_messageInfo_ItemList proto.InternalMessageInfo

func (m *ItemList) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Root struct {
	Index                uint64   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Root                 []byte   `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Root) Reset()         { *m = Root{} }
func (m *Root) String() string { return proto.CompactTextString(m) }
func (*Root) ProtoMessage()    {}
func (*Root) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{7}
}

func (m *Root) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Root.Unmarshal(m, b)
}
func (m *Root) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Root.Marshal(b, m, deterministic)
}
func (m *Root) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Root.Merge(m, src)
}
func (m *Root) XXX_Size() int {
	return xxx_messageInfo_Root.Size(m)
}
func (m *Root) XXX_DiscardUnknown() {
	xxx_messageInfo_Root.DiscardUnknown(m)
}

var xxx_messageInfo_Root proto.InternalMessageInfo

func (m *Root) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Root) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

type ScanOptions struct {
	Prefix               []byte   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Offset               []byte   `protobuf:"bytes,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                uint64   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Reverse              bool     `protobuf:"varint,4,opt,name=reverse,proto3" json:"reverse,omitempty"`
	Deep                 bool     `protobuf:"varint,5,opt,name=deep,proto3" json:"deep,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanOptions) Reset()         { *m = ScanOptions{} }
func (m *ScanOptions) String() string { return proto.CompactTextString(m) }
func (*ScanOptions) ProtoMessage()    {}
func (*ScanOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{8}
}

func (m *ScanOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanOptions.Unmarshal(m, b)
}
func (m *ScanOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanOptions.Marshal(b, m, deterministic)
}
func (m *ScanOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanOptions.Merge(m, src)
}
func (m *ScanOptions) XXX_Size() int {
	return xxx_messageInfo_ScanOptions.Size(m)
}
func (m *ScanOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ScanOptions proto.InternalMessageInfo

func (m *ScanOptions) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *ScanOptions) GetOffset() []byte {
	if m != nil {
		return m.Offset
	}
	return nil
}

func (m *ScanOptions) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ScanOptions) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

func (m *ScanOptions) GetDeep() bool {
	if m != nil {
		return m.Deep
	}
	return false
}

type KeyPrefix struct {
	Prefix               []byte   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyPrefix) Reset()         { *m = KeyPrefix{} }
func (m *KeyPrefix) String() string { return proto.CompactTextString(m) }
func (*KeyPrefix) ProtoMessage()    {}
func (*KeyPrefix) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{9}
}

func (m *KeyPrefix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyPrefix.Unmarshal(m, b)
}
func (m *KeyPrefix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyPrefix.Marshal(b, m, deterministic)
}
func (m *KeyPrefix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyPrefix.Merge(m, src)
}
func (m *KeyPrefix) XXX_Size() int {
	return xxx_messageInfo_KeyPrefix.Size(m)
}
func (m *KeyPrefix) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyPrefix.DiscardUnknown(m)
}

var xxx_messageInfo_KeyPrefix proto.InternalMessageInfo

func (m *KeyPrefix) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

type ItemsCount struct {
	Count                uint64   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemsCount) Reset()         { *m = ItemsCount{} }
func (m *ItemsCount) String() string { return proto.CompactTextString(m) }
func (*ItemsCount) ProtoMessage()    {}
func (*ItemsCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{10}
}

func (m *ItemsCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemsCount.Unmarshal(m, b)
}
func (m *ItemsCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemsCount.Marshal(b, m, deterministic)
}
func (m *ItemsCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemsCount.Merge(m, src)
}
func (m *ItemsCount) XXX_Size() int {
	return xxx_messageInfo_ItemsCount.Size(m)
}
func (m *ItemsCount) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemsCount.DiscardUnknown(m)
}

var xxx_messageInfo_ItemsCount proto.InternalMessageInfo

func (m *ItemsCount) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type InclusionProof struct {
	At                   uint64   `protobuf:"varint,1,opt,name=at,proto3" json:"at,omitempty"`
	Index                uint64   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Root                 []byte   `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	Leaf                 []byte   `protobuf:"bytes,4,opt,name=leaf,proto3" json:"leaf,omitempty"`
	Path                 [][]byte `protobuf:"bytes,5,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InclusionProof) Reset()         { *m = InclusionProof{} }
func (m *InclusionProof) String() string { return proto.CompactTextString(m) }
func (*InclusionProof) ProtoMessage()    {}
func (*InclusionProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{11}
}

func (m *InclusionProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InclusionProof.Unmarshal(m, b)
}
func (m *InclusionProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InclusionProof.Marshal(b, m, deterministic)
}
func (m *InclusionProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InclusionProof.Merge(m, src)
}
func (m *InclusionProof) XXX_Size() int {
	return xxx_messageInfo_InclusionProof.Size(m)
}
func (m *InclusionProof) XXX_DiscardUnknown() {
	xxx_messageInfo_InclusionProof.DiscardUnknown(m)
}

var xxx_messageInfo_InclusionProof proto.InternalMessageInfo

func (m *InclusionProof) GetAt() uint64 {
	if m != nil {
		return m.At
	}
	return 0
}

func (m *InclusionProof) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *InclusionProof) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *InclusionProof) GetLeaf() []byte {
	if m != nil {
		return m.Leaf
	}
	return nil
}

func (m *InclusionProof) GetPath() [][]byte {
	if m != nil {
		return m.Path
	}
	return nil
}

type ConsistencyProof struct {
	First                uint64   `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Second               uint64   `protobuf:"varint,2,opt,name=second,proto3" json:"second,omitempty"`
	FirstRoot            []byte   `protobuf:"bytes,3,opt,name=firstRoot,proto3" json:"firstRoot,omitempty"`
	SecondRoot           []byte   `protobuf:"bytes,4,opt,name=secondRoot,proto3" json:"secondRoot,omitempty"`
	Path                 [][]byte `protobuf:"bytes,5,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsistencyProof) Reset()         { *m = ConsistencyProof{} }
func (m *ConsistencyProof) String() string { return proto.CompactTextString(m) }
func (*ConsistencyProof) ProtoMessage()    {}
func (*ConsistencyProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{12}
}

func (m *ConsistencyProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsistencyProof.Unmarshal(m, b)
}
func (m *ConsistencyProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsistencyProof.Marshal(b, m, deterministic)
}
func (m *ConsistencyProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsistencyProof.Merge(m, src)
}
func (m *ConsistencyProof) XXX_Size() int {
	return xxx_messageInfo_ConsistencyProof.Size(m)
}
func (m *ConsistencyProof) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsistencyProof.DiscardUnknown(m)
}

var xxx_messageInfo_ConsistencyProof proto.InternalMessageInfo

func (m *ConsistencyProof) GetFirst() uint64 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *ConsistencyProof) GetSecond() uint64 {
	if m != nil {
		return m.Second
	}
	return 0
}

func (m *ConsistencyProof) GetFirstRoot() []byte {
	if m != nil {
		return m.FirstRoot
	}
	return nil
}

func (m *ConsistencyProof) GetSecondRoot() []byte {
	if m != nil {
		return m.SecondRoot
	}
	return nil
}

func (m *ConsistencyProof) GetPath() [][]byte {
	if m != nil {
		return m.Path
	}
	return nil
}

type Proof struct {
	Leaf                 []byte   `protobuf:"bytes,1,opt,name=leaf,proto3" json:"leaf,omitempty"`
	Index                uint64   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Root                 []byte   `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	At                   uint64   `protobuf:"varint,4,opt,name=at,proto3" json:"at,omitempty"`
	InclusionPath        [][]byte `protobuf:"bytes,5,rep,name=inclusionPath,proto3" json:"inclusionPath,omitempty"`
	ConsistencyPath      [][]byte `protobuf:"bytes,6,rep,name=consistencyPath,proto3" json:"consistencyPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proof) Reset()         { *m = Proof{} }
func (m *Proof) String() string { return proto.CompactTextString(m) }
func (*Proof) ProtoMessage()    {}
func (*Proof) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{13}
}

func (m *Proof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proof.Unmarshal(m, b)
}
func (m *Proof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proof.Marshal(b, m, deterministic)
}
func (m *Proof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proof.Merge(m, src)
}
func (m *Proof) XXX_Size() int {
	return xxx_messageInfo_Proof.Size(m)
}
func (m *Proof) XXX_DiscardUnknown() {
	xxx_messageInfo_Proof.DiscardUnknown(m)
}

var xxx_messageInfo_Proof proto.InternalMessageInfo

func (m *Proof) GetLeaf() []byte {
	if m != nil {
		return m.Leaf
	}
	return nil
}

func (m *Proof) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Proof) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *Proof) GetAt() uint64 {
	if m != nil {
		return m.At
	}
	return 0
}

func (m *Proof) GetInclusionPath() [][]byte {
	if m != nil {
		return m.InclusionPath
	}
	return nil
}

func (m *Proof) GetConsistencyPath() [][]byte {
	if m != nil {
		return m.ConsistencyPath
	}
	return nil
}

type SafeItem struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Proof                *Proof   `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SafeItem) Reset()         { *m = SafeItem{} }
func (m *SafeItem) String() string { return proto.CompactTextString(m) }
func (*SafeItem) ProtoMessage()    {}
func (*SafeItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{14}
}

func (m *SafeItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeItem.Unmarshal(m, b)
}
func (m *SafeItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeItem.Marshal(b, m, deterministic)
}
func (m *SafeItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeItem.Merge(m, src)
}
func (m *SafeItem) XXX_Size() int {
	return xxx_messageInfo_SafeItem.Size(m)
}
func (m *SafeItem) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeItem.DiscardUnknown(m)
}

var xxx_messageInfo_SafeItem proto.InternalMessageInfo

func (m *SafeItem) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *SafeItem) GetProof() *Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

type SafeSetOptions struct {
	Kv                   *KeyValue `protobuf:"bytes,1,opt,name=kv,proto3" json:"kv,omitempty"`
	RootIndex            *Index    `protobuf:"bytes,2,opt,name=rootIndex,proto3" json:"rootIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SafeSetOptions) Reset()         { *m = SafeSetOptions{} }
func (m *SafeSetOptions) String() string { return proto.CompactTextString(m) }
func (*SafeSetOptions) ProtoMessage()    {}
func (*SafeSetOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{15}
}

func (m *SafeSetOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeSetOptions.Unmarshal(m, b)
}
func (m *SafeSetOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeSetOptions.Marshal(b, m, deterministic)
}
func (m *SafeSetOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeSetOptions.Merge(m, src)
}
func (m *SafeSetOptions) XXX_Size() int {
	return xxx_messageInfo_SafeSetOptions.Size(m)
}
func (m *SafeSetOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeSetOptions.DiscardUnknown(m)
}

var xxx_messageInfo_SafeSetOptions proto.InternalMessageInfo

func (m *SafeSetOptions) GetKv() *KeyValue {
	if m != nil {
		return m.Kv
	}
	return nil
}

func (m *SafeSetOptions) GetRootIndex() *Index {
	if m != nil {
		return m.RootIndex
	}
	return nil
}

type SafeGetOptions struct {
	Key                  *Key     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RootIndex            *Index   `protobuf:"bytes,2,opt,name=rootIndex,proto3" json:"rootIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SafeGetOptions) Reset()         { *m = SafeGetOptions{} }
func (m *SafeGetOptions) String() string { return proto.CompactTextString(m) }
func (*SafeGetOptions) ProtoMessage()    {}
func (*SafeGetOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{16}
}

func (m *SafeGetOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeGetOptions.Unmarshal(m, b)
}
func (m *SafeGetOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeGetOptions.Marshal(b, m, deterministic)
}
func (m *SafeGetOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeGetOptions.Merge(m, src)
}
func (m *SafeGetOptions) XXX_Size() int {
	return xxx_messageInfo_SafeGetOptions.Size(m)
}
func (m *SafeGetOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeGetOptions.DiscardUnknown(m)
}

var xxx_messageInfo_SafeGetOptions proto.InternalMessageInfo

func (m *SafeGetOptions) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SafeGetOptions) GetRootIndex() *Index {
	if m != nil {
		return m.RootIndex
	}
	return nil
}

type SafeReferenceOptions struct {
	Ro                   *ReferenceOptions `protobuf:"bytes,1,opt,name=ro,proto3" json:"ro,omitempty"`
	RootIndex            *Index            `protobuf:"bytes,2,opt,name=rootIndex,proto3" json:"rootIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SafeReferenceOptions) Reset()         { *m = SafeReferenceOptions{} }
func (m *SafeReferenceOptions) String() string { return proto.CompactTextString(m) }
func (*SafeReferenceOptions) ProtoMessage()    {}
func (*SafeReferenceOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{17}
}

func (m *SafeReferenceOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeReferenceOptions.Unmarshal(m, b)
}
func (m *SafeReferenceOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeReferenceOptions.Marshal(b, m, deterministic)
}
func (m *SafeReferenceOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeReferenceOptions.Merge(m, src)
}
func (m *SafeReferenceOptions) XXX_Size() int {
	return xxx_messageInfo_SafeReferenceOptions.Size(m)
}
func (m *SafeReferenceOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeReferenceOptions.DiscardUnknown(m)
}

var xxx_messageInfo_SafeReferenceOptions proto.InternalMessageInfo

func (m *SafeReferenceOptions) GetRo() *ReferenceOptions {
	if m != nil {
		return m.Ro
	}
	return nil
}

func (m *SafeReferenceOptions) GetRootIndex() *Index {
	if m != nil {
		return m.RootIndex
	}
	return nil
}

type HealthResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthResponse) Reset()         { *m = HealthResponse{} }
func (m *HealthResponse) String() string { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()    {}
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{18}
}

func (m *HealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthResponse.Unmarshal(m, b)
}
func (m *HealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthResponse.Marshal(b, m, deterministic)
}
func (m *HealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResponse.Merge(m, src)
}
func (m *HealthResponse) XXX_Size() int {
	return xxx_messageInfo_HealthResponse.Size(m)
}
func (m *HealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResponse proto.InternalMessageInfo

func (m *HealthResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type ReferenceOptions struct {
	Reference            *Key     `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Key                  *Key     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReferenceOptions) Reset()         { *m = ReferenceOptions{} }
func (m *ReferenceOptions) String() string { return proto.CompactTextString(m) }
func (*ReferenceOptions) ProtoMessage()    {}
func (*ReferenceOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{19}
}

func (m *ReferenceOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferenceOptions.Unmarshal(m, b)
}
func (m *ReferenceOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferenceOptions.Marshal(b, m, deterministic)
}
func (m *ReferenceOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferenceOptions.Merge(m, src)
}
func (m *ReferenceOptions) XXX_Size() int {
	return xxx_messageInfo_ReferenceOptions.Size(m)
}
func (m *ReferenceOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferenceOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ReferenceOptions proto.InternalMessageInfo

func (m *ReferenceOptions) GetReference() *Key {
	if m != nil {
		return m.Reference
	}
	return nil
}

func (m *ReferenceOptions) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

//
//Why use double as score type?
//Because it is not purely about the storage size, but also use cases.
//64-bit floating point double gives a lot of flexibility and dynamic range, at the expense of having only 53-bits of integer.
type ZAddOptions struct {
	Set                  []byte   `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
	Score                float64  `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Key                  []byte   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZAddOptions) Reset()         { *m = ZAddOptions{} }
func (m *ZAddOptions) String() string { return proto.CompactTextString(m) }
func (*ZAddOptions) ProtoMessage()    {}
func (*ZAddOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{20}
}

func (m *ZAddOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZAddOptions.Unmarshal(m, b)
}
func (m *ZAddOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZAddOptions.Marshal(b, m, deterministic)
}
func (m *ZAddOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZAddOptions.Merge(m, src)
}
func (m *ZAddOptions) XXX_Size() int {
	return xxx_messageInfo_ZAddOptions.Size(m)
}
func (m *ZAddOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ZAddOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ZAddOptions proto.InternalMessageInfo

func (m *ZAddOptions) GetSet() []byte {
	if m != nil {
		return m.Set
	}
	return nil
}

func (m *ZAddOptions) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ZAddOptions) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type ZScanOptions struct {
	Set                  []byte   `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
	Offset               []byte   `protobuf:"bytes,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                uint64   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Reverse              bool     `protobuf:"varint,4,opt,name=reverse,proto3" json:"reverse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZScanOptions) Reset()         { *m = ZScanOptions{} }
func (m *ZScanOptions) String() string { return proto.CompactTextString(m) }
func (*ZScanOptions) ProtoMessage()    {}
func (*ZScanOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{21}
}

func (m *ZScanOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZScanOptions.Unmarshal(m, b)
}
func (m *ZScanOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZScanOptions.Marshal(b, m, deterministic)
}
func (m *ZScanOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZScanOptions.Merge(m, src)
}
func (m *ZScanOptions) XXX_Size() int {
	return xxx_messageInfo_ZScanOptions.Size(m)
}
func (m *ZScanOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ZScanOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ZScanOptions proto.InternalMessageInfo

func (m *ZScanOptions) GetSet() []byte {
	if m != nil {
		return m.Set
	}
	return nil
}

func (m *ZScanOptions) GetOffset() []byte {
	if m != nil {
		return m.Offset
	}
	return nil
}

func (m *ZScanOptions) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ZScanOptions) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

type SafeZAddOptions struct {
	Zopts                *ZAddOptions `protobuf:"bytes,1,opt,name=zopts,proto3" json:"zopts,omitempty"`
	RootIndex            *Index       `protobuf:"bytes,2,opt,name=rootIndex,proto3" json:"rootIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SafeZAddOptions) Reset()         { *m = SafeZAddOptions{} }
func (m *SafeZAddOptions) String() string { return proto.CompactTextString(m) }
func (*SafeZAddOptions) ProtoMessage()    {}
func (*SafeZAddOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{22}
}

func (m *SafeZAddOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeZAddOptions.Unmarshal(m, b)
}
func (m *SafeZAddOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeZAddOptions.Marshal(b, m, deterministic)
}
func (m *SafeZAddOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeZAddOptions.Merge(m, src)
}
func (m *SafeZAddOptions) XXX_Size() int {
	return xxx_messageInfo_SafeZAddOptions.Size(m)
}
func (m *SafeZAddOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeZAddOptions.DiscardUnknown(m)
}

var xxx_messageInfo_SafeZAddOptions proto.InternalMessageInfo

func (m *SafeZAddOptions) GetZopts() *ZAddOptions {
	if m != nil {
		return m.Zopts
	}
	return nil
}

func (m *SafeZAddOptions) GetRootIndex() *Index {
	if m != nil {
		return m.RootIndex
	}
	return nil
}

func init() {
	proto.RegisterType((*Key)(nil), "immudb.schema.Key")
	proto.RegisterType((*KeyValue)(nil), "immudb.schema.KeyValue")
	proto.RegisterType((*Index)(nil), "immudb.schema.Index")
	proto.RegisterType((*Item)(nil), "immudb.schema.Item")
	proto.RegisterType((*KVList)(nil), "immudb.schema.KVList")
	proto.RegisterType((*KeyList)(nil), "immudb.schema.KeyList")
	proto.RegisterType((*ItemList)(nil), "immudb.schema.ItemList")
	proto.RegisterType((*Root)(nil), "immudb.schema.Root")
	proto.RegisterType((*ScanOptions)(nil), "immudb.schema.ScanOptions")
	proto.RegisterType((*KeyPrefix)(nil), "immudb.schema.KeyPrefix")
	proto.RegisterType((*ItemsCount)(nil), "immudb.schema.ItemsCount")
	proto.RegisterType((*InclusionProof)(nil), "immudb.schema.InclusionProof")
	proto.RegisterType((*ConsistencyProof)(nil), "immudb.schema.ConsistencyProof")
	proto.RegisterType((*Proof)(nil), "immudb.schema.Proof")
	proto.RegisterType((*SafeItem)(nil), "immudb.schema.SafeItem")
	proto.RegisterType((*SafeSetOptions)(nil), "immudb.schema.SafeSetOptions")
	proto.RegisterType((*SafeGetOptions)(nil), "immudb.schema.SafeGetOptions")
	proto.RegisterType((*SafeReferenceOptions)(nil), "immudb.schema.SafeReferenceOptions")
	proto.RegisterType((*HealthResponse)(nil), "immudb.schema.HealthResponse")
	proto.RegisterType((*ReferenceOptions)(nil), "immudb.schema.ReferenceOptions")
	proto.RegisterType((*ZAddOptions)(nil), "immudb.schema.ZAddOptions")
	proto.RegisterType((*ZScanOptions)(nil), "immudb.schema.ZScanOptions")
	proto.RegisterType((*SafeZAddOptions)(nil), "immudb.schema.SafeZAddOptions")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_1c5fb4d8cc22d66a) }

var fileDescriptor_1c5fb4d8cc22d66a = []byte{
	// 1292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x97, 0x5d, 0x6e, 0xdb, 0x46,
	0x10, 0x80, 0xa1, 0x3f, 0x5b, 0x1a, 0x39, 0x8e, 0xb1, 0x75, 0x6d, 0x55, 0x76, 0x1c, 0x65, 0xe3,
	0xc4, 0xaa, 0x93, 0x88, 0x8e, 0x82, 0xbe, 0xf4, 0xad, 0x49, 0x0b, 0xc7, 0x50, 0x81, 0x06, 0x74,
	0x91, 0x02, 0xee, 0x43, 0x40, 0x51, 0x2b, 0x89, 0x91, 0xc4, 0x25, 0xc8, 0x95, 0x62, 0xc6, 0xc8,
	0x43, 0x7b, 0x84, 0xf6, 0x0c, 0xbd, 0x41, 0x6f, 0xd2, 0x2b, 0xf4, 0x20, 0xc5, 0xce, 0x92, 0x12,
	0x45, 0xad, 0x64, 0xc7, 0xe8, 0x1b, 0x77, 0x77, 0x38, 0xdf, 0xcc, 0x70, 0xe7, 0x87, 0xb0, 0x11,
	0xd8, 0x7d, 0x36, 0xb2, 0x1a, 0x9e, 0xcf, 0x05, 0x27, 0x77, 0x9c, 0xd1, 0x68, 0xdc, 0x69, 0x37,
	0xd4, 0x66, 0x75, 0xbf, 0xc7, 0x79, 0x6f, 0xc8, 0x0c, 0xcb, 0x73, 0x0c, 0xcb, 0x75, 0xb9, 0xb0,
	0x84, 0xc3, 0xdd, 0x40, 0x09, 0x57, 0xf7, 0xa2, 0x53, 0x5c, 0xb5, 0xc7, 0x5d, 0x83, 0x8d, 0x3c,
	0x11, 0xaa, 0x43, 0xba, 0x0b, 0xb9, 0x16, 0x0b, 0xc9, 0x16, 0xe4, 0x06, 0x2c, 0xac, 0x64, 0x6a,
	0x99, 0xfa, 0x86, 0x29, 0x1f, 0x69, 0x13, 0x8a, 0x2d, 0x16, 0xbe, 0xb5, 0x86, 0x63, 0xb6, 0x78,
	0x4a, 0xb6, 0xa1, 0x30, 0x91, 0x47, 0x95, 0x2c, 0xee, 0xa9, 0x05, 0xbd, 0x07, 0x85, 0x33, 0xb7,
	0xc3, 0x2e, 0xe5, 0xb1, 0x23, 0x1f, 0xf0, 0x95, 0xbc, 0xa9, 0x16, 0xf4, 0x7b, 0xc8, 0x9f, 0x09,
	0x36, 0xba, 0xa9, 0xba, 0x99, 0x96, 0x5c, 0x52, 0xcb, 0x0b, 0x58, 0x6b, 0xbd, 0xfd, 0xd1, 0x09,
	0x04, 0xf9, 0x1a, 0x72, 0xad, 0xb7, 0x41, 0x25, 0x53, 0xcb, 0xd5, 0xcb, 0xcd, 0xdd, 0xc6, 0x5c,
	0x4c, 0x1a, 0xb1, 0xf1, 0xa6, 0x94, 0xa1, 0xcf, 0x61, 0xbd, 0xc5, 0x42, 0x7c, 0xeb, 0x31, 0xe4,
	0x07, 0x2c, 0x8c, 0x5f, 0x23, 0x8b, 0xaf, 0x99, 0x78, 0x4e, 0xbf, 0x81, 0xa2, 0xb4, 0x36, 0x22,
	0x15, 0x1c, 0xc1, 0x46, 0xf1, 0x4b, 0x5f, 0xa4, 0x5e, 0x92, 0x72, 0xa6, 0x92, 0xa0, 0x27, 0x90,
	0x37, 0x39, 0x17, 0xfa, 0x10, 0x10, 0x02, 0x79, 0x9f, 0x73, 0x11, 0xf9, 0x89, 0xcf, 0xf4, 0xb7,
	0x0c, 0x94, 0xcf, 0x6d, 0xcb, 0xfd, 0xc9, 0xc3, 0xaf, 0x46, 0x76, 0x60, 0xcd, 0xf3, 0x59, 0xd7,
	0xb9, 0x8c, 0x22, 0x14, 0xad, 0xe4, 0x3e, 0xef, 0x76, 0x03, 0x16, 0xbf, 0x1d, 0xad, 0x24, 0x69,
	0xe8, 0x8c, 0x1c, 0x11, 0x87, 0x09, 0x17, 0xa4, 0x02, 0xeb, 0x3e, 0x9b, 0x30, 0x3f, 0x60, 0x95,
	0x7c, 0x2d, 0x53, 0x2f, 0x9a, 0xf1, 0x52, 0xda, 0xd0, 0x61, 0xcc, 0xab, 0x14, 0x70, 0x1b, 0x9f,
	0xe9, 0x43, 0x28, 0xb5, 0x58, 0xf8, 0x66, 0x0a, 0xd2, 0x19, 0x40, 0x29, 0x80, 0xf4, 0x34, 0x78,
	0xc5, 0xc7, 0x2e, 0x62, 0x6d, 0xf9, 0x10, 0x3b, 0x88, 0x0b, 0xea, 0xc3, 0xe6, 0x99, 0x6b, 0x0f,
	0xc7, 0x81, 0xc3, 0xdd, 0x37, 0x3e, 0xe7, 0x5d, 0xb2, 0x09, 0x59, 0x2b, 0x16, 0xca, 0x5a, 0x89,
	0xc0, 0x64, 0x75, 0x81, 0xc9, 0xcd, 0x02, 0x23, 0xf7, 0x86, 0xcc, 0xea, 0xa2, 0xfd, 0x1b, 0x26,
	0x3e, 0xcb, 0x3d, 0xcf, 0x12, 0xfd, 0x4a, 0xa1, 0x96, 0x93, 0x7b, 0xf2, 0x99, 0xfe, 0x91, 0x81,
	0xad, 0x57, 0xdc, 0x0d, 0x9c, 0x40, 0x30, 0xd7, 0x0e, 0x15, 0x76, 0x1b, 0x0a, 0x5d, 0xc7, 0x0f,
	0xa6, 0xe6, 0xe1, 0x42, 0xba, 0x16, 0x30, 0x9b, 0xbb, 0x9d, 0x88, 0x1e, 0xad, 0xc8, 0x3e, 0x94,
	0x50, 0xc0, 0x9c, 0xd9, 0x30, 0xdb, 0x20, 0x07, 0x00, 0x4a, 0x0e, 0x8f, 0x95, 0x39, 0x89, 0x1d,
	0xad, 0x51, 0x7f, 0x65, 0xa0, 0xa0, 0x2c, 0x89, 0xdd, 0xc8, 0x24, 0xdc, 0xb8, 0x79, 0x10, 0x54,
	0xf8, 0xf2, 0xd3, 0xf0, 0x1d, 0xc2, 0x1d, 0x67, 0x1a, 0xe0, 0x19, 0x74, 0x7e, 0x93, 0xd4, 0xe1,
	0xae, 0x9d, 0x88, 0x88, 0x94, 0x5b, 0x43, 0xb9, 0xf4, 0x36, 0x7d, 0x07, 0xc5, 0x73, 0xab, 0xcb,
	0x30, 0x31, 0x8f, 0x20, 0x2f, 0x2f, 0x31, 0x5a, 0xba, 0xe4, 0x96, 0xa3, 0x00, 0x39, 0x86, 0x82,
	0x27, 0x7d, 0x43, 0xf3, 0xcb, 0xcd, 0xed, 0x94, 0x24, 0xfa, 0x6d, 0x2a, 0x11, 0x3a, 0x82, 0x4d,
	0x09, 0x38, 0x67, 0x22, 0xbe, 0xe0, 0x47, 0x90, 0x1d, 0x4c, 0x22, 0xc8, 0xd2, 0xb4, 0xcd, 0x0e,
	0x26, 0xa4, 0x09, 0x25, 0x19, 0x83, 0xb3, 0x69, 0xa4, 0x16, 0x51, 0x78, 0x66, 0xce, 0xc4, 0xe8,
	0x7b, 0x85, 0x3b, 0x9d, 0xe1, 0x0e, 0x67, 0xe5, 0x46, 0x9f, 0xef, 0x58, 0x82, 0x6e, 0xc3, 0xba,
	0x82, 0x6d, 0xc9, 0x32, 0x59, 0x97, 0xf9, 0xcc, 0xb5, 0x59, 0x4c, 0x34, 0x20, 0xeb, 0xf3, 0x08,
	0x78, 0x3f, 0xa5, 0x24, 0x2d, 0x6c, 0x66, 0x7d, 0x7e, 0x2b, 0x78, 0x1d, 0x36, 0x5f, 0x33, 0x6b,
	0x28, 0xfa, 0x26, 0x0b, 0x3c, 0xee, 0x06, 0x0c, 0x2f, 0xb7, 0xb0, 0xc4, 0x38, 0x40, 0x74, 0xd1,
	0x8c, 0x56, 0xf4, 0x3d, 0x6c, 0x2d, 0x98, 0x78, 0x02, 0x25, 0x3f, 0xde, 0x5b, 0x11, 0x9a, 0x99,
	0x50, 0x1c, 0xc6, 0xec, 0xca, 0x30, 0xd2, 0x53, 0x28, 0x5f, 0x7c, 0xd7, 0xe9, 0xc4, 0x98, 0x2d,
	0xc8, 0xc9, 0x82, 0x15, 0x95, 0xfa, 0xa8, 0x5a, 0x05, 0x36, 0xf7, 0x55, 0xa9, 0xcf, 0x98, 0x6a,
	0x11, 0xb7, 0x84, 0xdc, 0xac, 0xff, 0xf4, 0x61, 0xe3, 0x22, 0x59, 0x15, 0x17, 0x35, 0xfd, 0x4f,
	0xf5, 0x90, 0x7e, 0x80, 0xbb, 0xf2, 0x2b, 0x26, 0xcd, 0x3e, 0x81, 0xc2, 0x47, 0xee, 0x89, 0x20,
	0x8a, 0x4c, 0x35, 0xe5, 0x6d, 0x42, 0xd4, 0x54, 0x82, 0xb7, 0xf9, 0x82, 0xcd, 0xbf, 0xef, 0x42,
	0xf9, 0x6c, 0x34, 0x1a, 0x9f, 0x33, 0x7f, 0xe2, 0xd8, 0x8c, 0xfc, 0x02, 0xb9, 0x73, 0x26, 0xc8,
	0xb2, 0x94, 0xa8, 0x6a, 0x15, 0xd2, 0x07, 0xbf, 0xff, 0xf3, 0xef, 0x9f, 0xd9, 0x3d, 0xba, 0x63,
	0x4c, 0x9e, 0x1b, 0x52, 0xc0, 0x67, 0x81, 0xf0, 0x7c, 0x7e, 0x19, 0x1a, 0x32, 0x57, 0xbf, 0xcd,
	0x1c, 0x93, 0x2e, 0xac, 0x47, 0x29, 0x48, 0xee, 0xa5, 0x74, 0xcc, 0xa7, 0x66, 0x55, 0x9b, 0xc9,
	0xf4, 0x31, 0x22, 0x6a, 0x74, 0x4f, 0x8f, 0x30, 0x02, 0xab, 0xcb, 0x24, 0xe7, 0x67, 0xc8, 0x9d,
	0x32, 0x41, 0x34, 0x97, 0xa3, 0xaa, 0x2b, 0x26, 0xf4, 0x10, 0xf5, 0x1e, 0x90, 0xfd, 0x25, 0x7a,
	0xaf, 0x06, 0x2c, 0xfc, 0x44, 0x46, 0xca, 0xfa, 0xd3, 0x25, 0xd6, 0xcf, 0x32, 0xbd, 0xba, 0xab,
	0x39, 0x46, 0xd0, 0x31, 0x82, 0x0e, 0xe9, 0xfd, 0x15, 0x0e, 0x18, 0x3d, 0x26, 0xa4, 0x13, 0xb2,
	0x20, 0x32, 0xf1, 0xd2, 0x12, 0x76, 0x9f, 0x7c, 0x99, 0xf6, 0x04, 0x07, 0x8f, 0x25, 0x1f, 0x62,
	0x45, 0x94, 0xda, 0x52, 0x9b, 0x11, 0x28, 0x80, 0x0d, 0xc5, 0xd3, 0x18, 0xb0, 0xb3, 0x18, 0x2a,
	0x24, 0xec, 0x6a, 0xc2, 0x25, 0x0f, 0xae, 0x87, 0xf4, 0x62, 0x48, 0x5e, 0x66, 0x0f, 0x49, 0x5f,
	0xdd, 0x44, 0x4a, 0xdd, 0x0a, 0xa2, 0xc2, 0x65, 0x5b, 0xae, 0x84, 0x0c, 0xa0, 0xa0, 0x66, 0x81,
	0xca, 0xa2, 0x1b, 0x6a, 0x96, 0xa8, 0x7e, 0xa5, 0x61, 0xa8, 0x01, 0x82, 0x3e, 0x43, 0xca, 0x11,
	0x79, 0xb4, 0x84, 0x82, 0x03, 0x85, 0x71, 0xa5, 0x86, 0x8f, 0x4f, 0xe4, 0x02, 0xca, 0xaf, 0xc6,
	0xbe, 0xcf, 0x5c, 0xd5, 0x93, 0x77, 0x1a, 0x6a, 0xac, 0x6d, 0xc4, 0x63, 0x6d, 0xe3, 0x07, 0x39,
	0xd6, 0x2e, 0x5c, 0x34, 0x29, 0x4c, 0x0f, 0x10, 0x55, 0x21, 0x9a, 0x1c, 0xc1, 0x26, 0xeb, 0x43,
	0x69, 0x3a, 0xb5, 0x10, 0xed, 0xd7, 0xad, 0xde, 0x5b, 0xd8, 0x4d, 0x4e, 0x39, 0xf4, 0x04, 0x09,
	0xc7, 0xa4, 0xae, 0x71, 0x26, 0x96, 0xc4, 0x7e, 0x68, 0x5c, 0x61, 0xaf, 0xff, 0x44, 0x2e, 0xa1,
	0x9c, 0x18, 0x5a, 0x96, 0x50, 0xd3, 0xdd, 0x23, 0x3d, 0xe6, 0xd0, 0x26, 0x72, 0x9f, 0x92, 0xe3,
	0x45, 0x6e, 0xa2, 0xd3, 0xcf, 0x93, 0xdb, 0xb0, 0xfe, 0x32, 0x8c, 0x06, 0x75, 0x2d, 0x55, 0x9b,
	0xac, 0x4f, 0x91, 0xf4, 0x98, 0x1c, 0x2e, 0xf9, 0x5c, 0xa8, 0x7c, 0xca, 0x78, 0x07, 0xeb, 0xaf,
	0x9d, 0x40, 0x70, 0x3f, 0xd4, 0x96, 0x83, 0xa5, 0x57, 0xef, 0x08, 0x29, 0x0f, 0x88, 0x26, 0x53,
	0xfb, 0x4a, 0x5f, 0x54, 0x15, 0x1c, 0x58, 0x53, 0xed, 0x6f, 0xe9, 0x4d, 0x48, 0x7f, 0xb1, 0xf9,
	0x6e, 0x49, 0xeb, 0x48, 0xa2, 0xa4, 0xa6, 0x21, 0xa1, 0xa4, 0x1f, 0xf7, 0xd5, 0xf7, 0x50, 0x9a,
	0xf6, 0x4f, 0x72, 0x5d, 0x3f, 0xff, 0xfc, 0xe2, 0x30, 0x6d, 0xb1, 0x32, 0xa5, 0x3e, 0xc0, 0x9d,
	0xb9, 0x91, 0x82, 0x3c, 0xd4, 0xd4, 0xb4, 0x6b, 0x99, 0xea, 0x6e, 0x3c, 0x41, 0xe6, 0x23, 0xaa,
	0xf1, 0x10, 0x0b, 0xde, 0x1c, 0xf8, 0x57, 0xc8, 0xcb, 0xb6, 0x46, 0x56, 0xf4, 0xba, 0xcf, 0x6f,
	0x40, 0x1f, 0xad, 0x4e, 0x47, 0x2a, 0xb7, 0xa0, 0x80, 0xcd, 0x9c, 0xec, 0xa5, 0xb5, 0xdf, 0xa8,
	0x1e, 0x51, 0x24, 0xec, 0xd3, 0x5d, 0x0d, 0x21, 0xae, 0x45, 0x7d, 0x35, 0xc7, 0xa2, 0x0f, 0x07,
	0x9a, 0x98, 0xad, 0xf2, 0xe3, 0xda, 0x2e, 0x87, 0xe1, 0x8a, 0x9c, 0x79, 0xf9, 0xec, 0xe2, 0x49,
	0xcf, 0x11, 0xfd, 0x71, 0xbb, 0x61, 0x73, 0x59, 0xa5, 0x3a, 0x4c, 0xfe, 0x71, 0xfb, 0xa1, 0xa1,
	0x94, 0x1a, 0xde, 0xa0, 0x87, 0x7f, 0xe2, 0x4a, 0x79, 0x7b, 0x0d, 0xaf, 0xe5, 0x8b, 0xff, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xa7, 0x3b, 0xbd, 0xaa, 0xc2, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ImmuServiceClient is the client API for ImmuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ImmuServiceClient interface {
	Set(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Index, error)
	SafeSet(ctx context.Context, in *SafeSetOptions, opts ...grpc.CallOption) (*Proof, error)
	Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Item, error)
	SafeGet(ctx context.Context, in *SafeGetOptions, opts ...grpc.CallOption) (*SafeItem, error)
	SetBatch(ctx context.Context, in *KVList, opts ...grpc.CallOption) (*Index, error)
	GetBatch(ctx context.Context, in *KeyList, opts ...grpc.CallOption) (*ItemList, error)
	Scan(ctx context.Context, in *ScanOptions, opts ...grpc.CallOption) (*ItemList, error)
	Count(ctx context.Context, in *KeyPrefix, opts ...grpc.CallOption) (*ItemsCount, error)
	CurrentRoot(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Root, error)
	Inclusion(ctx context.Context, in *Index, opts ...grpc.CallOption) (*InclusionProof, error)
	Consistency(ctx context.Context, in *Index, opts ...grpc.CallOption) (*ConsistencyProof, error)
	ByIndex(ctx context.Context, in *Index, opts ...grpc.CallOption) (*Item, error)
	History(ctx context.Context, in *Key, opts ...grpc.CallOption) (*ItemList, error)
	Health(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	Reference(ctx context.Context, in *ReferenceOptions, opts ...grpc.CallOption) (*Index, error)
	SafeReference(ctx context.Context, in *SafeReferenceOptions, opts ...grpc.CallOption) (*Proof, error)
	ZAdd(ctx context.Context, in *ZAddOptions, opts ...grpc.CallOption) (*Index, error)
	ZScan(ctx context.Context, in *ZScanOptions, opts ...grpc.CallOption) (*ItemList, error)
	SafeZAdd(ctx context.Context, in *SafeZAddOptions, opts ...grpc.CallOption) (*Proof, error)
}

type immuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImmuServiceClient(cc grpc.ClientConnInterface) ImmuServiceClient {
	return &immuServiceClient{cc}
}

func (c *immuServiceClient) Set(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Index, error) {
	out := new(Index)
	err := c.cc.Invoke(ctx, "/immudb.schema.ImmuService/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) SafeSet(ctx context.Context, in *SafeSetOptions, opts ...grpc.CallOption) (*Proof, error) {
	out := new(Proof)
	err := c.cc.Invoke(ctx, "/immudb.schema.ImmuService/SafeSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := c.cc.Invoke(ctx, "/immudb.schema.ImmuService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) SafeGet(ctx context.Context, in *SafeGetOptions, opts ...grpc.CallOption) (*SafeItem, error) {
	out := new(SafeItem)
	err := c.cc.Invoke(ctx, "/immudb.schema.ImmuService/SafeGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) SetBatch(ctx context.Context, in *KVList, opts ...grpc.CallOption) (*Index, error) {
	out := new(Index)
	err := c.cc.Invoke(ctx, "/immudb.schema.ImmuService/SetBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) GetBatch(ctx context.Context, in *KeyList, opts ...grpc.CallOption) (*ItemList, error) {
	out := new(ItemList)
	err := c.cc.Invoke(ctx, "/immudb.schema.ImmuService/GetBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) Scan(ctx context.Context, in *ScanOptions, opts ...grpc.CallOption) (*ItemList, error) {
	out := new(ItemList)
	err := c.cc.Invoke(ctx, "/immudb.schema.ImmuService/Scan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) Count(ctx context.Context, in *KeyPrefix, opts ...grpc.CallOption) (*ItemsCount, error) {
	out := new(ItemsCount)
	err := c.cc.Invoke(ctx, "/immudb.schema.ImmuService/Count", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) CurrentRoot(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Root, error) {
	out := new(Root)
	err := c.cc.Invoke(ctx, "/immudb.schema.ImmuService/CurrentRoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) Inclusion(ctx context.Context, in *Index, opts ...grpc.CallOption) (*InclusionProof, error) {
	out := new(InclusionProof)
	err := c.cc.Invoke(ctx, "/immudb.schema.ImmuService/Inclusion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) Consistency(ctx context.Context, in *Index, opts ...grpc.CallOption) (*ConsistencyProof, error) {
	out := new(ConsistencyProof)
	err := c.cc.Invoke(ctx, "/immudb.schema.ImmuService/Consistency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) ByIndex(ctx context.Context, in *Index, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := c.cc.Invoke(ctx, "/immudb.schema.ImmuService/ByIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) History(ctx context.Context, in *Key, opts ...grpc.CallOption) (*ItemList, error) {
	out := new(ItemList)
	err := c.cc.Invoke(ctx, "/immudb.schema.ImmuService/History", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) Health(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/immudb.schema.ImmuService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) Reference(ctx context.Context, in *ReferenceOptions, opts ...grpc.CallOption) (*Index, error) {
	out := new(Index)
	err := c.cc.Invoke(ctx, "/immudb.schema.ImmuService/Reference", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) SafeReference(ctx context.Context, in *SafeReferenceOptions, opts ...grpc.CallOption) (*Proof, error) {
	out := new(Proof)
	err := c.cc.Invoke(ctx, "/immudb.schema.ImmuService/SafeReference", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) ZAdd(ctx context.Context, in *ZAddOptions, opts ...grpc.CallOption) (*Index, error) {
	out := new(Index)
	err := c.cc.Invoke(ctx, "/immudb.schema.ImmuService/ZAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) ZScan(ctx context.Context, in *ZScanOptions, opts ...grpc.CallOption) (*ItemList, error) {
	out := new(ItemList)
	err := c.cc.Invoke(ctx, "/immudb.schema.ImmuService/ZScan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *immuServiceClient) SafeZAdd(ctx context.Context, in *SafeZAddOptions, opts ...grpc.CallOption) (*Proof, error) {
	out := new(Proof)
	err := c.cc.Invoke(ctx, "/immudb.schema.ImmuService/SafeZAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImmuServiceServer is the server API for ImmuService service.
type ImmuServiceServer interface {
	Set(context.Context, *KeyValue) (*Index, error)
	SafeSet(context.Context, *SafeSetOptions) (*Proof, error)
	Get(context.Context, *Key) (*Item, error)
	SafeGet(context.Context, *SafeGetOptions) (*SafeItem, error)
	SetBatch(context.Context, *KVList) (*Index, error)
	GetBatch(context.Context, *KeyList) (*ItemList, error)
	Scan(context.Context, *ScanOptions) (*ItemList, error)
	Count(context.Context, *KeyPrefix) (*ItemsCount, error)
	CurrentRoot(context.Context, *empty.Empty) (*Root, error)
	Inclusion(context.Context, *Index) (*InclusionProof, error)
	Consistency(context.Context, *Index) (*ConsistencyProof, error)
	ByIndex(context.Context, *Index) (*Item, error)
	History(context.Context, *Key) (*ItemList, error)
	Health(context.Context, *empty.Empty) (*HealthResponse, error)
	Reference(context.Context, *ReferenceOptions) (*Index, error)
	SafeReference(context.Context, *SafeReferenceOptions) (*Proof, error)
	ZAdd(context.Context, *ZAddOptions) (*Index, error)
	ZScan(context.Context, *ZScanOptions) (*ItemList, error)
	SafeZAdd(context.Context, *SafeZAddOptions) (*Proof, error)
}

// UnimplementedImmuServiceServer can be embedded to have forward compatible implementations.
type UnimplementedImmuServiceServer struct {
}

func (*UnimplementedImmuServiceServer) Set(ctx context.Context, req *KeyValue) (*Index, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (*UnimplementedImmuServiceServer) SafeSet(ctx context.Context, req *SafeSetOptions) (*Proof, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SafeSet not implemented")
}
func (*UnimplementedImmuServiceServer) Get(ctx context.Context, req *Key) (*Item, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedImmuServiceServer) SafeGet(ctx context.Context, req *SafeGetOptions) (*SafeItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SafeGet not implemented")
}
func (*UnimplementedImmuServiceServer) SetBatch(ctx context.Context, req *KVList) (*Index, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBatch not implemented")
}
func (*UnimplementedImmuServiceServer) GetBatch(ctx context.Context, req *KeyList) (*ItemList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBatch not implemented")
}
func (*UnimplementedImmuServiceServer) Scan(ctx context.Context, req *ScanOptions) (*ItemList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Scan not implemented")
}
func (*UnimplementedImmuServiceServer) Count(ctx context.Context, req *KeyPrefix) (*ItemsCount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Count not implemented")
}
func (*UnimplementedImmuServiceServer) CurrentRoot(ctx context.Context, req *empty.Empty) (*Root, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurrentRoot not implemented")
}
func (*UnimplementedImmuServiceServer) Inclusion(ctx context.Context, req *Index) (*InclusionProof, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Inclusion not implemented")
}
func (*UnimplementedImmuServiceServer) Consistency(ctx context.Context, req *Index) (*ConsistencyProof, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Consistency not implemented")
}
func (*UnimplementedImmuServiceServer) ByIndex(ctx context.Context, req *Index) (*Item, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ByIndex not implemented")
}
func (*UnimplementedImmuServiceServer) History(ctx context.Context, req *Key) (*ItemList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method History not implemented")
}
func (*UnimplementedImmuServiceServer) Health(ctx context.Context, req *empty.Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (*UnimplementedImmuServiceServer) Reference(ctx context.Context, req *ReferenceOptions) (*Index, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reference not implemented")
}
func (*UnimplementedImmuServiceServer) SafeReference(ctx context.Context, req *SafeReferenceOptions) (*Proof, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SafeReference not implemented")
}
func (*UnimplementedImmuServiceServer) ZAdd(ctx context.Context, req *ZAddOptions) (*Index, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZAdd not implemented")
}
func (*UnimplementedImmuServiceServer) ZScan(ctx context.Context, req *ZScanOptions) (*ItemList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZScan not implemented")
}
func (*UnimplementedImmuServiceServer) SafeZAdd(ctx context.Context, req *SafeZAddOptions) (*Proof, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SafeZAdd not implemented")
}

func RegisterImmuServiceServer(s *grpc.Server, srv ImmuServiceServer) {
	s.RegisterService(&_ImmuService_serviceDesc, srv)
}

func _ImmuService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/immudb.schema.ImmuService/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).Set(ctx, req.(*KeyValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_SafeSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SafeSetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).SafeSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/immudb.schema.ImmuService/SafeSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).SafeSet(ctx, req.(*SafeSetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/immudb.schema.ImmuService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).Get(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_SafeGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SafeGetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).SafeGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/immudb.schema.ImmuService/SafeGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).SafeGet(ctx, req.(*SafeGetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_SetBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).SetBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/immudb.schema.ImmuService/SetBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).SetBatch(ctx, req.(*KVList))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_GetBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).GetBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/immudb.schema.ImmuService/GetBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).GetBatch(ctx, req.(*KeyList))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/immudb.schema.ImmuService/Scan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).Scan(ctx, req.(*ScanOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyPrefix)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/immudb.schema.ImmuService/Count",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).Count(ctx, req.(*KeyPrefix))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_CurrentRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).CurrentRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/immudb.schema.ImmuService/CurrentRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).CurrentRoot(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_Inclusion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Index)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).Inclusion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/immudb.schema.ImmuService/Inclusion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).Inclusion(ctx, req.(*Index))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_Consistency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Index)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).Consistency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/immudb.schema.ImmuService/Consistency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).Consistency(ctx, req.(*Index))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_ByIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Index)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).ByIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/immudb.schema.ImmuService/ByIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).ByIndex(ctx, req.(*Index))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_History_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).History(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/immudb.schema.ImmuService/History",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).History(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/immudb.schema.ImmuService/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).Health(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_Reference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReferenceOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).Reference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/immudb.schema.ImmuService/Reference",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).Reference(ctx, req.(*ReferenceOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_SafeReference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SafeReferenceOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).SafeReference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/immudb.schema.ImmuService/SafeReference",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).SafeReference(ctx, req.(*SafeReferenceOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_ZAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZAddOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).ZAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/immudb.schema.ImmuService/ZAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).ZAdd(ctx, req.(*ZAddOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_ZScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZScanOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).ZScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/immudb.schema.ImmuService/ZScan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).ZScan(ctx, req.(*ZScanOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImmuService_SafeZAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SafeZAddOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImmuServiceServer).SafeZAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/immudb.schema.ImmuService/SafeZAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImmuServiceServer).SafeZAdd(ctx, req.(*SafeZAddOptions))
	}
	return interceptor(ctx, in, info, handler)
}

var _ImmuService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "immudb.schema.ImmuService",
	HandlerType: (*ImmuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _ImmuService_Set_Handler,
		},
		{
			MethodName: "SafeSet",
			Handler:    _ImmuService_SafeSet_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ImmuService_Get_Handler,
		},
		{
			MethodName: "SafeGet",
			Handler:    _ImmuService_SafeGet_Handler,
		},
		{
			MethodName: "SetBatch",
			Handler:    _ImmuService_SetBatch_Handler,
		},
		{
			MethodName: "GetBatch",
			Handler:    _ImmuService_GetBatch_Handler,
		},
		{
			MethodName: "Scan",
			Handler:    _ImmuService_Scan_Handler,
		},
		{
			MethodName: "Count",
			Handler:    _ImmuService_Count_Handler,
		},
		{
			MethodName: "CurrentRoot",
			Handler:    _ImmuService_CurrentRoot_Handler,
		},
		{
			MethodName: "Inclusion",
			Handler:    _ImmuService_Inclusion_Handler,
		},
		{
			MethodName: "Consistency",
			Handler:    _ImmuService_Consistency_Handler,
		},
		{
			MethodName: "ByIndex",
			Handler:    _ImmuService_ByIndex_Handler,
		},
		{
			MethodName: "History",
			Handler:    _ImmuService_History_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ImmuService_Health_Handler,
		},
		{
			MethodName: "Reference",
			Handler:    _ImmuService_Reference_Handler,
		},
		{
			MethodName: "SafeReference",
			Handler:    _ImmuService_SafeReference_Handler,
		},
		{
			MethodName: "ZAdd",
			Handler:    _ImmuService_ZAdd_Handler,
		},
		{
			MethodName: "ZScan",
			Handler:    _ImmuService_ZScan_Handler,
		},
		{
			MethodName: "SafeZAdd",
			Handler:    _ImmuService_SafeZAdd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schema.proto",
}
