name: build
on:
  push:
    branches:
      - main
    tags:
      - v*
    pull_request:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '15'
    - name: Build
      run: |
        npm install
        npm run build --if-present
        npm run generate
    - name: pack
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        tar zcf immudb-webconsole.tar.gz dist
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: immudb-webconsole.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
