FROM golang:1.19 as builder
WORKDIR /src/immudb-tools
RUN git clone https://github.com/codenotary/immudb-tools .
RUN (cd stresser2 && go build)
RUN (cd paralsql && go build)

FROM debian:stable-slim
COPY --from=builder /src/immudb-tools/stresser2/stresser2 /src/immudb-tools/paralsql/paralsql /usr/local/bin
ENTRYPOINT ["/bin/bash", "-c"]
CMD ["echo hello world"]

