name: immudb Stress
on:
  pull_request:
    branches:
    - '**'

jobs:
  stress-build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup runner for Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.13
    - uses: actions/checkout@v3
    - name: Build stress tool
      run: |
        go build embedded/tools/stress_tool/stress_tool.go
    - name: "| Entries: 1M | Workers: 20  | Batch: 1k | Batches: 50 |"
      run: |
        rm -rf data
        ./stress_tool -mode auto -committers 20 -kvCount 1000 -txCount 50 -txRead -synced
    - name: "| Entries: 1M | Workers: 50  | Batch: 1k | Batches: 20 |"
      run: |
        rm -rf data
        ./stress_tool -mode auto -committers 50 -kvCount 1000 -txCount 20 -txRead -synced
    - name: "| Entries: 1M | Workers: 100 | Batch: 1k | Batches: 10 |"
      run: |
        rm -rf data
        ./stress_tool -mode auto -committers 100 -kvCount 1000 -txCount 10 -txRead -synced
